# Generated by Django 6.0.2 on 2026-03-01 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagestory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Image Stories'},
        ),
        migrations.AddField(
            model_name='imagestory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagestory',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('tamil', 'Tamil'), ('telugu', 'Telugu')], default='english', max_length=50),
        ),
    ]
