# Generated by Django 6.0.2 on 2026-03-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_imagestory_options_imagestory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestory',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='imagestory',
            name='cartoon_image',
            field=models.ImageField(blank=True, null=True, upload_to='cartoons/'),
        ),
    ]
